# .github/workflows/main.yaml
name: CI & Deploy (Vue + Vite)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write      # needed for deploy to GitHub Pages
  id-token: write   # needed for deploy to GitHub Pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # --- Optional: spin up json-server for tests (CI only) ---
      # - name: Start json-server (CI)
      #   run: |
      #     npx json-server --watch db.json --port 3001 &
      #     echo "Waiting for json-server..."
      #     npx wait-on http://localhost:3001
      # ----------------------------------------------------------

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Unit tests (if present)
        run: npm test --if-present

      - name: Build (Vite)
        run: npm run build

      - name: Upload Pages artifact (dist)
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
